services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DNS_NAME=${DNS_NAME}
    volumes:
      - ./static:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  latexai:
    build:
      context: ./latexAI
    container_name: latex-ai
    ports:
      - "5000:5000"
    restart: unless-stopped

  latex-api:
    build: 
      context: ./latex-api
    container_name: latex-server
    ports:
      - "4001:4001"
    volumes:
      - /var/pdflatex:/workdir/output
    restart: unless-stopped


