# Use official Python image
FROM python:3.9

# Set the working directory inside the container
WORKDIR /app

# Install Flask directly using pip
RUN pip install --no-cache-dir flask fpdf

# Copy the application files
COPY . .

# Expose port 4000
EXPOSE 4000

# Define the command to run the Flask app
CMD ["python", "app.py"]

